# Generated by Django 3.2.7 on 2021-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='patient',
            name='Surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
