# Generated by Django 3.2.7 on 2021-10-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_appointments_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('appointment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('IdDoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_specialist',
            field=models.CharField(choices=[('Flu', 'Flu'), ('Diabetes', 'Diabetes'), ('Corona_virus', 'Corona_virus')], max_length=200, null=True),
        ),
    ]
