# Generated by Django 3.2.7 on 2021-10-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211003_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('specialization', models.CharField(choices=[('Flu', 'Flu'), ('Diabetes', 'Diabetes'), ('Corona_virus', 'Corona_virus')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_specialist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.specialization'),
        ),
    ]
