# Generated by Django 3.2.7 on 2021-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment_reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
