# Generated by Django 3.2.7 on 2021-10-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_patient_appointment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='username',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='doctor',
        ),
    ]
