# Generated by Django 3.2.7 on 2021-10-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
