# Generated by Django 3.2.7 on 2021-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_admin_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checking for available time', 'Checking for available time'), ('Resolved', 'Resolved')], max_length=200, null=True),
        ),
    ]
