# Generated by Django 3.2.7 on 2021-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_appointment_id_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
